---
# # tasks file for kubernetes_network
# - name: Install Flannel network plugin
#   shell: su - $ANSIBLE_USER -c "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
#   become: true

# - name: Taint master node to prevent workload scheduling
#   shell: su - $ANSIBLE_USER -c "kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule --overwrite"
#   become: true

# tasks file for kubernetes_network
- name: Installer le plugin réseau Calico
  shell: su - $ANSIBLE_USER -c "kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.26.1/manifests/calico.yaml"
  become: true

- name: Taint master node to prevent workload scheduling
  shell: su - $ANSIBLE_USER -c "kubectl taint nodes --all node-role.kubernetes.io/control-plane:NoSchedule --overwrite"
  become: true
