---
- name: Install dependencies (Debian/Ubuntu)
  apt:
    name:
      - openjdk-11-jdk
      - wget
      - gnupg
      - software-properties-common
    state: present
  when: ansible_os_family == "Debian"

- name: Install dependencies (RedHat/CentOS)
  yum:
    name:
      - java-11-openjdk-devel
      - wget
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Jenkins repository key (Debian/Ubuntu)
  apt_key:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
    state: present
  when: ansible_os_family == "Debian"

- name: Add Jenkins repository (Debian/Ubuntu)
  apt_repository:
    repo: "deb https://pkg.jenkins.io/debian-stable binary/"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Jenkins repository (RedHat/CentOS)
  yum_repository:
    name: jenkins
    description: Jenkins Repository
    baseurl: https://pkg.jenkins.io/redhat-stable/
    gpgkey: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
    gpgcheck: yes
  when: ansible_os_family == "RedHat"

- name: Install Jenkins
  package:
    name: jenkins
    state: present

- name: Start and enable Jenkins service
  service:
    name: jenkins
    state: started
    enabled: yes

- name: Wait for Jenkins to initialize
  wait_for:
    port: "{{ jenkins_port }}"
    delay: 10
    timeout: 300

- name: Display Jenkins initial admin password
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password

- name: Print Jenkins initial admin password
  debug:
    msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"